const { Factory, loadInstance } = require("./Factory");
const {
  RARITY_DELIMITER,
  randomColor,
  rarity,
  removeRarity,
  rarityWeightedChoice,
  pinDirectoryToIPFS,
  pinFileToIPFS,
  verifyContract,
  getPaths,
  getPrefixes,
  reducePaths,
  computeNs,
  expandPathIfNeeded,
  append,
  composeImages,
  layersNames,
  name,
  sizeOf,
  compose,
} = require("./utils");

module.exports = {
  Factory,
  RARITY_DELIMITER,
  randomColor,
  rarity,
  removeRarity,
  rarityWeightedChoice,
  pinDirectoryToIPFS,
  pinFileToIPFS,
  verifyContract,
  getPaths,
  getPrefixes,
  reducePaths,
  computeNs,
  expandPathIfNeeded,
  append,
  composeImages,
  loadInstance,
  layersNames,
  name,
  sizeOf,
  compose,
};
